REM ========================================================================
REM =  Texas Instruments
REM =  Run this batch file before attempting to build from a command line.
REM =  This file is automatically generated during installation.
REM ========================================================================
REM =  If you get an "Out of Environment Space" error message running this batch 
REM =  file on Windows 98 or Windows Me type the following line at the C:\CCStudio_v3.3> prompt 
REM =  to start a new copy of the Windows Command Interpreter with 2K of Environment Space.
 
REM      COMMAND /E:2048
 
REM ========================================================================
SET PATH=C:\ti\ccsv5\tools\compiler\c5500_4.4.1\bin;%PATH%;
rem SET TI_DIR=C:\CCStudio_v3.3
SET C55X_A_DIR="C:\ti\ccsv5\tools\compiler\c5500_4.4.1\include";"C:\ti\ccsv5\tools\compiler\c5500_4.4.1\lib"
SET C55X_C_DIR="C:\ti\ccsv5\tools\compiler\c5500_4.4.1\include";"C:\ti\ccsv5\tools\compiler\c5500_4.4.1\lib"
